//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVEntities : DbContext
    {
        public CVEntities()
            : base("name=CVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLABOUT> TBLABOUT { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
        public virtual DbSet<TBLCERTIFICATES> TBLCERTIFICATES { get; set; }
        public virtual DbSet<TBLEDUCATION> TBLEDUCATION { get; set; }
        public virtual DbSet<TBLEXPERIENCE> TBLEXPERIENCE { get; set; }
        public virtual DbSet<TBLINTERESTS> TBLINTERESTS { get; set; }
        public virtual DbSet<TBLSKILLS> TBLSKILLS { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLSOCIALMEDIA> TBLSOCIALMEDIA { get; set; }
    }
}
