//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSOCIALMEDIA
    {
        public int ID { get; set; }
        public string ACCOUNT { get; set; }
        public string LINK { get; set; }
        public string ICON { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
